rows = 10
columns = 20
just_ate = False
run_add_fruit = True
chosen_position = [4,4]
positions = [[0,0],[1,0],[2,0]] #tail ---> head
direction = "right"
chosen_direction = None
score = 0
snake_char = "O"
empty_char = "-"
fruit_char = "X"